#ifndef SCANNER_H
#define SCANNER_H

#include <vector>
#include <iostream>
#include <sstream>

#include <FlexLexer.h>

/*
  This file defines the wrapper class which acts
  as interfaces to the code generated by lex
 
  It depends on flex generating scanner classes, 
  which is a feature which may be removed in 
  a future release ( of flex ).

  This solution is still preferable to the 
  purely C reentrant scanners because there
  is no possibility of a shared scanner state
  at all.
*/

namespace slurp {
  class SlurpScanner : public yyFlexLexer {
      std::vector<std::string> results;
    public:
      SlurpScanner( std::istream* arg_yyin, std::ostream* arg_yyout ) 
         : yyFlexLexer( arg_yyin, arg_yyout ) 
      {
          /* stub */
      }
      int yylex(); 
      inline void addResult( std::string res ) {
         results.push_back(res);
      }
  };
}

#endif
